.golangci.yml, pkg/claim/schema_test.go
Having made some changes to the linter configuration of
'test-network-function' this copies over the updates to
this repo.
They may diverge in the future but at this point there is
not a strong reason for them to so I will favour consistency.
Signed-off-by: Charlie Wheeler-Robinson <cwheeler@redhat.com>
=> match linter config from 'test-network-function'

claim.schema.json
This change updates the schema with enhanced and more informative
descriptions.  Additionally, since OpenShift version may vary between
nodes, it was found that it is better suited to belong in the "nodes"
section.  Thus, it was removed from the "versions" section.
=> Update the descriptions in claim.schema.json

claim.schema.json
Versions became mismatched between schema and Go module.
Re-align them appropriately.
=> Manually add version tag

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Go 1.17.3 is now [available](https://twitter.com/golang/status/1456314310330880004).
Includes security fixes to archive/zip and debug/macho (CVE-2021-41772, CVE-2021-41771).
=> Go 1.17.3 update

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Go 1.17.6 is now available.
https://twitter.com/golang/status/1479199301352013829
From their release page:
```
go1.17.6 (released 2022-01-06) includes fixes to the compiler, linker, runtime, and the crypto/x509, net/http, and reflect packages. See the Go 1.17.6 milestone on our issue tracker for details.
```
=> Update Go to 1.17.6

.golangci.yml, Makefile, README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.44.1
No code changes found/needed.
=> Bump GolangCI-lint to v1.44.1

.golangci.yml, README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.45.2
Similar to:
https://github.com/test-network-function/cnf-certification-test/pull/92
https://github.com/test-network-function/test-network-function/pull/660
https://github.com/test-network-function/cnfcert-tests-verification/pull/55
=> Update GolangCI to 1.45.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml, README.md, go.mod
Similar to:
https://github.com/test-network-function/cnf-certification-test/pull/129
The linter throws warnings due to [this issue](https://github.com/golangci/golangci-lint/issues/2649) but doesn't cause failures.
=> Upgrade to Go 1.18.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://github.com/actions/setup-go/releases/tag/v3.0.0
v3 is the latest available release of `setup-go`.
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/205
=> Upgrade to v3 setup-go action

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://groups.google.com/g/golang-announce/c/xtuG5faxtaU
Security: Includes security fixes for archive/tar (CVE-2022-2879), net/http (CVE-2022-2880), and regexp (CVE-2022-41715).
Related to: https://github.com/test-network-function/cnf-certification-test/pull/571
=> Update Go to v1.19.2

.golangci.yml, README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.50.0
Related to: https://github.com/test-network-function/cnf-certification-test/pull/604
=> Upgrade Golangci-lint to v1.50.0

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://groups.google.com/g/golang-announce/c/wrmRT7JlevE
Related to: https://github.com/test-network-function/cnf-certification-test/pull/779
=> Update Go to v1.19.5

.golangci.yml, README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.51.0
Related to: https://github.com/test-network-function/cnf-certification-test/pull/837
=> Update GolangCI to v1.51.0

pkg/claim/catalog.go
The previous func:
```
func formTestURL(suite, name string) string {
return fmt.Sprintf("%s/%s/%s", url, suite, name)
}
```
Used to build the TestURL with a combination of the suite name and the test name with a "/" in the middle.  Returning some of that functionality.
=> Slight modification to the testID

README.md
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1236
https://github.com/golangci/golangci-lint/releases/tag/v1.53.3
=> Update GolangCI-lint to v1.53.3

.github/workflows/merge.yml, .github/workflows/pre-main.yml, README.md, go.mod
https://go.dev/doc/go1.21
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1344
=> Update Go to v1.21.0

.golangci.yml, README.md
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1892
=> Update GolangCI-lint to v1.56.2

.golangci.yml
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2598
=> Update GolangCI-lint to v1.62

.golangci.yml, README.md
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2667
=> Update GolangCI-lint to v1.63.3

.golangci.yml, README.md
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2792
=> Updating GolangCI to v1.64.2
