redhat-best-practices-for-k8s/certsuite-claim

README.md
=> Add info pertaining to the choice of a single tnf version

schemas/claim.example.json
Signed-off-by: David Spence <dspence@redhat.com>
=> An example claim output, based upon truncated real data.

.github/workflows/merge.yml
=> fix the merge job

README.md
=> add merge/report card badges

.github/workflows/pre-main.yml
=> Run unit tests for each PR

.golangci.yml, README.md, cmd/generate/generate.go, internal/generate/config.go, pkg/claim/schema_test.go
https://github.com/golangci/golangci-lint/releases/tag/v1.43.0
The linter raised some various fixes that needed addressing as well.
Related to: https://github.com/test-network-function/test-network-function/pull/476
=> GolangCI v1.43.0; fixes

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://go.dev/doc/devel/release
=> Update Go to 1.17.5

.github/workflows/pre-main.yml, Makefile
Related to: https://github.com/test-network-function/test-network-function/pull/552
Sets the coverage threshold to 40%.  Adjustable later.
=> Add unit test coverage gate; coverage-html make path

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://groups.google.com/g/golang-announce/c/RP1hfrBYVuk/m/I7ouYouLAAAJ
Similar to:
- https://github.com/test-network-function/cnfcert-tests-verification/pull/47
- https://github.com/test-network-function/test-network-function/pull/643
- https://github.com/test-network-function/cnf-certification-test-partner/pull/88
- https://github.com/test-network-function/cnf-certification-test/pull/51
=> Update Go to 1.17.8

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://github.com/golang/go/issues?q=milestone%3AGo1.17.9+label%3ACherryPickApproved
=> Update Go to 1.17.9

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://releases.ubuntu.com/22.04/
LTS 22.04 is available "Jammy Jellyfish".
=> Upgrade Ubuntu release to 22.04

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Release notes: https://groups.google.com/g/golang-announce/c/Y5qrqw_lWdU?pli=1
=> Upgrade Go to v1.18.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://groups.google.com/g/golang-announce/c/TzIC9-t8Ytg
=> Update Go to 1.18.3

.github/workflows/merge.yml, .github/workflows/pre-main.yml, README.md, go.mod
https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
Related to: https://github.com/test-network-function/cnf-certification-test/pull/531
=> Upgrade Go to v1.19.1

README.md
Related to: https://github.com/test-network-function/cnf-certification-test/pull/617
=> Update GolangCI-Lint to v1.50.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml
https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU
=> Update Go to v1.19.4

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/864
https://groups.google.com/g/golang-announce/c/V0aBFqaFs_E
=> Update Go to 1.19.6

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/924
=> Update Go to 1.20.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/927
=> Update setup-go action to v4

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/994
=> Update Go to v1.20.3

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1078
=> Update Go to v1.20.4

pkg/claim/catalog.go
Removing test type field from TestCaseDescription since the the CategoryClasssification already does the same and more
=> removing test type

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1242
=> Update Go to v1.20.6

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1315
=> Update Go to v1.20.7

.golangci.yml, README.md
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1367
=> Update GolangCI-lint to v1.54.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1387
=> Update Go to v1.21.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1504
=> Update Go to v1.21.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1558
=> Update Go to v1.21.3

.golangci.yml, README.md, cmd/generate/generate.go
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1575
=> Update GolangCI-lint to v1.55.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1598
=> Update Go to v1.21.4

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1697
=> Update Go to v1.21.5

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1804
=> Update Go to v1.21.6

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1873
=> Update Go to v1.21.7

.github/workflows/merge.yml, .github/workflows/pre-main.yml, README.md, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1902
=> Update Go to v1.22

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/1973
=> Update Go to v1.22.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2053
=> Update Go to v1.22.3

.golangci.yml, README.md, cmd/generate/generate.go
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2054
=> Update GolangCI-lint to v1.58.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml
Related to: 
- https://github.com/test-network-function/cnf-certification-test/pull/2079
=> Update ubuntu to 24.04

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2134
=> Update Go to v1.22.4

.golangci.yml, README.md
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2216
=> Update GolangCI-lint to v1.59.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/test-network-function/cnf-certification-test/pull/2229
=> Update Go to v1.22.5

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2360
=> Update Go to v1.22.6

.github/workflows/merge.yml, .github/workflows/pre-main.yml, README.md, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2402
=> Update Go to v1.23.1

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2482
=> Update Go to v1.23.2

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2594
=> Update Go to v1.23.3

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2609
=> Update Go to v1.23.4

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2704
=> Update Go to v1.23.5

.github/workflows/merge.yml, .github/workflows/pre-main.yml, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2766
=> Update Go to v1.23.6

.github/workflows/merge.yml, go.mod
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2855
=> Update Go to v1.24.1
